-- ============================================================
-- Migration: Seed zone metric registry with Census + derived keys
-- ============================================================

-- Ensure the full catalog schema columns exist before seeding.
-- zone_metric_registry may have been created by an earlier migration with a
-- narrower schema (metric_key, display_name, layer_category, source_type).
ALTER TABLE public.zone_metric_registry
  ADD COLUMN IF NOT EXISTS metric_label            text,
  ADD COLUMN IF NOT EXISTS metric_category         text,
  ADD COLUMN IF NOT EXISTS metric_family           text,
  ADD COLUMN IF NOT EXISTS value_type              text,
  ADD COLUMN IF NOT EXISTS source_scope            text,
  ADD COLUMN IF NOT EXISTS default_h3_resolution   integer,
  ADD COLUMN IF NOT EXISTS preferred_boundary_type text,
  ADD COLUMN IF NOT EXISTS is_derived              boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS source_priority         integer NOT NULL DEFAULT 100;

-- Backfill metric_label from legacy display_name for any pre-existing rows.
UPDATE public.zone_metric_registry
  SET metric_label = display_name
  WHERE metric_label IS NULL AND display_name IS NOT NULL;

INSERT INTO public.zone_metric_registry (
  metric_key,
  metric_label,
  metric_category,
  metric_family,
  value_type,
  units,
  source_scope,
  default_h3_resolution,
  preferred_boundary_type,
  is_derived,
  is_active,
  source_priority,
  description
)
VALUES
(
  'population_count',
  'Population Count',
  'demand',
  'population',
  'count',
  'people',
  'census_acs',
  7,
  'block_group',
  false,
  true,
  10,
  'Total resident population used as a base demand input and for downstream density calculations.'
),
(
  'household_count',
  'Household Count',
  'demand',
  'households',
  'count',
  'households',
  'census_acs',
  7,
  'block_group',
  false,
  true,
  10,
  'Total households used for residential demand surface modeling and household density calculations.'
),
(
  'population_density',
  'Population Density',
  'demand',
  'population',
  'ratio',
  'people_per_sq_mile',
  'derived',
  7,
  'block_group',
  true,
  true,
  20,
  'Derived metric calculated from population_count and the allocated H3 cell area.'
),
(
  'household_density',
  'Household Density',
  'demand',
  'households',
  'ratio',
  'households_per_sq_mile',
  'derived',
  7,
  'block_group',
  true,
  true,
  20,
  'Derived metric calculated from household_count and the allocated H3 cell area.'
),
(
  'median_household_income',
  'Median Household Income',
  'demand_quality',
  'income',
  'currency',
  'usd',
  'census_acs',
  7,
  'tract',
  false,
  true,
  10,
  'Median household income used as a proxy for discretionary spend, basket quality, and tip headroom.'
),
(
  'owner_household_count',
  'Owner Household Count',
  'housing',
  'tenure',
  'count',
  'households',
  'census_acs',
  7,
  'block_group',
  false,
  true,
  15,
  'Count of owner-occupied households from ACS tenure tables.'
),
(
  'renter_household_count',
  'Renter Household Count',
  'housing',
  'tenure',
  'count',
  'households',
  'census_acs',
  7,
  'block_group',
  false,
  true,
  15,
  'Count of renter-occupied households from ACS tenure tables.'
),
(
  'owner_share',
  'Owner Share',
  'housing',
  'tenure',
  'ratio',
  'share',
  'derived',
  7,
  'block_group',
  true,
  true,
  20,
  'Derived share of owner-occupied households relative to total occupied households.'
),
(
  'renter_share',
  'Renter Share',
  'housing',
  'tenure',
  'ratio',
  'share',
  'derived',
  7,
  'block_group',
  true,
  true,
  20,
  'Derived share of renter-occupied households relative to total occupied households.'
),
(
  'single_unit_detached_count',
  'Single Unit Detached Count',
  'housing',
  'structure',
  'count',
  'units',
  'census_acs',
  7,
  'block_group',
  false,
  true,
  15,
  'Count of housing units in detached single-unit structures.'
),
(
  'single_unit_attached_count',
  'Single Unit Attached Count',
  'housing',
  'structure',
  'count',
  'units',
  'census_acs',
  7,
  'block_group',
  false,
  true,
  15,
  'Count of housing units in attached single-unit structures.'
),
(
  'small_multifamily_count',
  'Small Multifamily Count',
  'housing',
  'structure',
  'count',
  'units',
  'census_acs',
  7,
  'block_group',
  false,
  true,
  15,
  'Count of units in smaller multifamily structures, typically 2 to 4 units.'
),
(
  'multifamily_5plus_count',
  'Multifamily 5 Plus Count',
  'housing',
  'structure',
  'count',
  'units',
  'census_acs',
  7,
  'block_group',
  false,
  true,
  15,
  'Count of housing units in structures with 5 or more units.'
),
(
  'large_structure_count',
  'Large Structure Count',
  'housing',
  'structure',
  'count',
  'units',
  'derived',
  7,
  'block_group',
  true,
  true,
  20,
  'Derived count of units in larger structures that are more likely to create delivery access friction.'
),
(
  'multifamily_share',
  'Multifamily Share',
  'friction',
  'access',
  'ratio',
  'share',
  'derived',
  7,
  'block_group',
  true,
  true,
  20,
  'Derived share of housing units in multifamily structures, used as an apartment-friction proxy.'
),
(
  'large_structure_share',
  'Large Structure Share',
  'friction',
  'access',
  'ratio',
  'share',
  'derived',
  7,
  'block_group',
  true,
  true,
  20,
  'Derived share of units in larger buildings, used as a building-entry and wayfinding friction proxy.'
),
(
  'high_rise_proxy',
  'High Rise Proxy',
  'friction',
  'access',
  'ratio',
  'index',
  'derived',
  7,
  'tract',
  true,
  true,
  25,
  'Derived proxy index representing likely high-rise or high-complexity residential delivery environments.'
),
(
  'worker_count',
  'Worker Count',
  'mobility',
  'commuting',
  'count',
  'workers',
  'census_acs',
  7,
  'tract',
  false,
  true,
  15,
  'Total worker population used for commute and daytime activity modeling.'
),
(
  'mean_commute_minutes',
  'Mean Commute Minutes',
  'mobility',
  'commuting',
  'ratio',
  'minutes',
  'census_acs',
  7,
  'tract',
  false,
  true,
  15,
  'Average commute duration used as a proxy for commuter-market behavior and office-driven timing effects.'
),
(
  'drive_alone_share',
  'Drive Alone Share',
  'mobility',
  'commuting',
  'ratio',
  'share',
  'derived',
  7,
  'tract',
  true,
  true,
  20,
  'Derived share of workers commuting by driving alone.'
),
(
  'public_transit_share',
  'Public Transit Share',
  'mobility',
  'commuting',
  'ratio',
  'share',
  'derived',
  7,
  'tract',
  true,
  true,
  20,
  'Derived share of workers commuting by public transit.'
),
(
  'work_from_home_share',
  'Work From Home Share',
  'mobility',
  'commuting',
  'ratio',
  'share',
  'derived',
  7,
  'tract',
  true,
  true,
  20,
  'Derived share of workers who work from home, useful for daytime at-home demand priors.'
),
(
  'age_18_24_share',
  'Age 18 to 24 Share',
  'demographic_profile',
  'age',
  'ratio',
  'share',
  'derived',
  7,
  'block_group',
  true,
  false,
  30,
  'Optional derived share for identifying student-heavy and late-night-prone areas.'
),
(
  'age_25_44_share',
  'Age 25 to 44 Share',
  'demographic_profile',
  'age',
  'ratio',
  'share',
  'derived',
  7,
  'block_group',
  true,
  false,
  30,
  'Optional derived share for identifying core working-age adult concentration.'
),
(
  'age_65_plus_share',
  'Age 65 Plus Share',
  'demographic_profile',
  'age',
  'ratio',
  'share',
  'derived',
  7,
  'block_group',
  true,
  false,
  30,
  'Optional derived share for identifying older population concentration.'
),
(
  'student_share',
  'Student Share',
  'demographic_profile',
  'education',
  'ratio',
  'share',
  'derived',
  7,
  'tract',
  true,
  false,
  30,
  'Optional derived share used to identify student-driven demand and college housing friction.'
),
(
  'zero_vehicle_household_share',
  'Zero Vehicle Household Share',
  'demand',
  'vehicle_availability',
  'ratio',
  'share',
  'derived',
  7,
  'block_group',
  true,
  false,
  30,
  'Optional derived share of households with no vehicle available, useful as a delivery-dependence proxy.'
),
(
  'broadband_access_share',
  'Broadband Access Share',
  'confidence',
  'digital_access',
  'ratio',
  'share',
  'derived',
  7,
  'tract',
  true,
  false,
  40,
  'Optional confidence modifier for sparse or rural markets based on broadband access.'
)
ON CONFLICT (metric_key) DO UPDATE
SET
  metric_label = EXCLUDED.metric_label,
  metric_category = EXCLUDED.metric_category,
  metric_family = EXCLUDED.metric_family,
  value_type = EXCLUDED.value_type,
  units = EXCLUDED.units,
  source_scope = EXCLUDED.source_scope,
  default_h3_resolution = EXCLUDED.default_h3_resolution,
  preferred_boundary_type = EXCLUDED.preferred_boundary_type,
  is_derived = EXCLUDED.is_derived,
  is_active = EXCLUDED.is_active,
  source_priority = EXCLUDED.source_priority,
  description = EXCLUDED.description,
  updated_at = now();
