import { CENSUS_METRIC_KEYS, type CensusMetricKey } from './census-metric-keys';
import { REFERENCE_METRIC_KEYS, type ReferenceMetricKey } from './reference-metric-keys';
import type { ZoneMetricDefinition } from './types';

export type ZoneMetricKey = CensusMetricKey | ReferenceMetricKey;

export const ZONE_METRIC_REGISTRY: Record<ZoneMetricKey, ZoneMetricDefinition> = {
  [CENSUS_METRIC_KEYS.POPULATION_COUNT]: {
    metricKey: CENSUS_METRIC_KEYS.POPULATION_COUNT,
    metricLabel: 'Population Count',
    metricCategory: 'demand',
    metricFamily: 'population',
    valueType: 'count',
    units: 'people',
    sourceScope: 'census_acs',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: false,
    isActive: true,
    sourcePriority: 10,
    description: 'Total resident population used as a base demand input and for downstream density calculations.',
  },
  [CENSUS_METRIC_KEYS.HOUSEHOLD_COUNT]: {
    metricKey: CENSUS_METRIC_KEYS.HOUSEHOLD_COUNT,
    metricLabel: 'Household Count',
    metricCategory: 'demand',
    metricFamily: 'households',
    valueType: 'count',
    units: 'households',
    sourceScope: 'census_acs',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: false,
    isActive: true,
    sourcePriority: 10,
    description: 'Total households used for residential demand surface modeling and household density calculations.',
  },
  [CENSUS_METRIC_KEYS.POPULATION_DENSITY]: {
    metricKey: CENSUS_METRIC_KEYS.POPULATION_DENSITY,
    metricLabel: 'Population Density',
    metricCategory: 'demand',
    metricFamily: 'population',
    valueType: 'ratio',
    units: 'people_per_sq_mile',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: true,
    isActive: true,
    sourcePriority: 20,
    description: 'Derived metric calculated from population_count and the allocated H3 cell area.',
  },
  [CENSUS_METRIC_KEYS.HOUSEHOLD_DENSITY]: {
    metricKey: CENSUS_METRIC_KEYS.HOUSEHOLD_DENSITY,
    metricLabel: 'Household Density',
    metricCategory: 'demand',
    metricFamily: 'households',
    valueType: 'ratio',
    units: 'households_per_sq_mile',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: true,
    isActive: true,
    sourcePriority: 20,
    description: 'Derived metric calculated from household_count and the allocated H3 cell area.',
  },
  [CENSUS_METRIC_KEYS.MEDIAN_HOUSEHOLD_INCOME]: {
    metricKey: CENSUS_METRIC_KEYS.MEDIAN_HOUSEHOLD_INCOME,
    metricLabel: 'Median Household Income',
    metricCategory: 'demand_quality',
    metricFamily: 'income',
    valueType: 'currency',
    units: 'usd',
    sourceScope: 'census_acs',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'tract',
    isDerived: false,
    isActive: true,
    sourcePriority: 10,
    description: 'Median household income used as a proxy for discretionary spend, basket quality, and tip headroom.',
  },
  [CENSUS_METRIC_KEYS.OWNER_HOUSEHOLD_COUNT]: {
    metricKey: CENSUS_METRIC_KEYS.OWNER_HOUSEHOLD_COUNT,
    metricLabel: 'Owner Household Count',
    metricCategory: 'housing',
    metricFamily: 'tenure',
    valueType: 'count',
    units: 'households',
    sourceScope: 'census_acs',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: false,
    isActive: true,
    sourcePriority: 15,
    description: 'Count of owner-occupied households from ACS tenure tables.',
  },
  [CENSUS_METRIC_KEYS.RENTER_HOUSEHOLD_COUNT]: {
    metricKey: CENSUS_METRIC_KEYS.RENTER_HOUSEHOLD_COUNT,
    metricLabel: 'Renter Household Count',
    metricCategory: 'housing',
    metricFamily: 'tenure',
    valueType: 'count',
    units: 'households',
    sourceScope: 'census_acs',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: false,
    isActive: true,
    sourcePriority: 15,
    description: 'Count of renter-occupied households from ACS tenure tables.',
  },
  [CENSUS_METRIC_KEYS.OWNER_SHARE]: {
    metricKey: CENSUS_METRIC_KEYS.OWNER_SHARE,
    metricLabel: 'Owner Share',
    metricCategory: 'housing',
    metricFamily: 'tenure',
    valueType: 'ratio',
    units: 'share',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: true,
    isActive: true,
    sourcePriority: 20,
    description: 'Derived share of owner-occupied households relative to total occupied households.',
  },
  [CENSUS_METRIC_KEYS.RENTER_SHARE]: {
    metricKey: CENSUS_METRIC_KEYS.RENTER_SHARE,
    metricLabel: 'Renter Share',
    metricCategory: 'housing',
    metricFamily: 'tenure',
    valueType: 'ratio',
    units: 'share',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: true,
    isActive: true,
    sourcePriority: 20,
    description: 'Derived share of renter-occupied households relative to total occupied households.',
  },
  [CENSUS_METRIC_KEYS.SINGLE_UNIT_DETACHED_COUNT]: {
    metricKey: CENSUS_METRIC_KEYS.SINGLE_UNIT_DETACHED_COUNT,
    metricLabel: 'Single Unit Detached Count',
    metricCategory: 'housing',
    metricFamily: 'structure',
    valueType: 'count',
    units: 'units',
    sourceScope: 'census_acs',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: false,
    isActive: true,
    sourcePriority: 15,
    description: 'Count of housing units in detached single-unit structures.',
  },
  [CENSUS_METRIC_KEYS.SINGLE_UNIT_ATTACHED_COUNT]: {
    metricKey: CENSUS_METRIC_KEYS.SINGLE_UNIT_ATTACHED_COUNT,
    metricLabel: 'Single Unit Attached Count',
    metricCategory: 'housing',
    metricFamily: 'structure',
    valueType: 'count',
    units: 'units',
    sourceScope: 'census_acs',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: false,
    isActive: true,
    sourcePriority: 15,
    description: 'Count of housing units in attached single-unit structures.',
  },
  [CENSUS_METRIC_KEYS.SMALL_MULTIFAMILY_COUNT]: {
    metricKey: CENSUS_METRIC_KEYS.SMALL_MULTIFAMILY_COUNT,
    metricLabel: 'Small Multifamily Count',
    metricCategory: 'housing',
    metricFamily: 'structure',
    valueType: 'count',
    units: 'units',
    sourceScope: 'census_acs',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: false,
    isActive: true,
    sourcePriority: 15,
    description: 'Count of units in smaller multifamily structures, typically 2 to 4 units.',
  },
  [CENSUS_METRIC_KEYS.MULTIFAMILY_5PLUS_COUNT]: {
    metricKey: CENSUS_METRIC_KEYS.MULTIFAMILY_5PLUS_COUNT,
    metricLabel: 'Multifamily 5 Plus Count',
    metricCategory: 'housing',
    metricFamily: 'structure',
    valueType: 'count',
    units: 'units',
    sourceScope: 'census_acs',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: false,
    isActive: true,
    sourcePriority: 15,
    description: 'Count of housing units in structures with 5 or more units.',
  },
  [CENSUS_METRIC_KEYS.LARGE_STRUCTURE_COUNT]: {
    metricKey: CENSUS_METRIC_KEYS.LARGE_STRUCTURE_COUNT,
    metricLabel: 'Large Structure Count',
    metricCategory: 'housing',
    metricFamily: 'structure',
    valueType: 'count',
    units: 'units',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: true,
    isActive: true,
    sourcePriority: 20,
    description: 'Derived count of units in larger structures that are more likely to create delivery access friction.',
  },
  [CENSUS_METRIC_KEYS.MULTIFAMILY_SHARE]: {
    metricKey: CENSUS_METRIC_KEYS.MULTIFAMILY_SHARE,
    metricLabel: 'Multifamily Share',
    metricCategory: 'friction',
    metricFamily: 'access',
    valueType: 'ratio',
    units: 'share',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: true,
    isActive: true,
    sourcePriority: 20,
    description: 'Derived share of housing units in multifamily structures, used as an apartment-friction proxy.',
  },
  [CENSUS_METRIC_KEYS.LARGE_STRUCTURE_SHARE]: {
    metricKey: CENSUS_METRIC_KEYS.LARGE_STRUCTURE_SHARE,
    metricLabel: 'Large Structure Share',
    metricCategory: 'friction',
    metricFamily: 'access',
    valueType: 'ratio',
    units: 'share',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: true,
    isActive: true,
    sourcePriority: 20,
    description: 'Derived share of units in larger buildings, used as a building-entry and wayfinding friction proxy.',
  },
  [CENSUS_METRIC_KEYS.HIGH_RISE_PROXY]: {
    metricKey: CENSUS_METRIC_KEYS.HIGH_RISE_PROXY,
    metricLabel: 'High Rise Proxy',
    metricCategory: 'friction',
    metricFamily: 'access',
    valueType: 'ratio',
    units: 'index',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'tract',
    isDerived: true,
    isActive: true,
    sourcePriority: 25,
    description: 'Derived proxy index representing likely high-rise or high-complexity residential delivery environments.',
  },
  [CENSUS_METRIC_KEYS.WORKER_COUNT]: {
    metricKey: CENSUS_METRIC_KEYS.WORKER_COUNT,
    metricLabel: 'Worker Count',
    metricCategory: 'mobility',
    metricFamily: 'commuting',
    valueType: 'count',
    units: 'workers',
    sourceScope: 'census_acs',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'tract',
    isDerived: false,
    isActive: true,
    sourcePriority: 15,
    description: 'Total worker population used for commute and daytime activity modeling.',
  },
  [CENSUS_METRIC_KEYS.MEAN_COMMUTE_MINUTES]: {
    metricKey: CENSUS_METRIC_KEYS.MEAN_COMMUTE_MINUTES,
    metricLabel: 'Mean Commute Minutes',
    metricCategory: 'mobility',
    metricFamily: 'commuting',
    valueType: 'ratio',
    units: 'minutes',
    sourceScope: 'census_acs',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'tract',
    isDerived: false,
    isActive: true,
    sourcePriority: 15,
    description: 'Average commute duration used as a proxy for commuter-market behavior and office-driven timing effects.',
  },
  [CENSUS_METRIC_KEYS.DRIVE_ALONE_SHARE]: {
    metricKey: CENSUS_METRIC_KEYS.DRIVE_ALONE_SHARE,
    metricLabel: 'Drive Alone Share',
    metricCategory: 'mobility',
    metricFamily: 'commuting',
    valueType: 'ratio',
    units: 'share',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'tract',
    isDerived: true,
    isActive: true,
    sourcePriority: 20,
    description: 'Derived share of workers commuting by driving alone.',
  },
  [CENSUS_METRIC_KEYS.PUBLIC_TRANSIT_SHARE]: {
    metricKey: CENSUS_METRIC_KEYS.PUBLIC_TRANSIT_SHARE,
    metricLabel: 'Public Transit Share',
    metricCategory: 'mobility',
    metricFamily: 'commuting',
    valueType: 'ratio',
    units: 'share',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'tract',
    isDerived: true,
    isActive: true,
    sourcePriority: 20,
    description: 'Derived share of workers commuting by public transit.',
  },
  [CENSUS_METRIC_KEYS.WORK_FROM_HOME_SHARE]: {
    metricKey: CENSUS_METRIC_KEYS.WORK_FROM_HOME_SHARE,
    metricLabel: 'Work From Home Share',
    metricCategory: 'mobility',
    metricFamily: 'commuting',
    valueType: 'ratio',
    units: 'share',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'tract',
    isDerived: true,
    isActive: true,
    sourcePriority: 20,
    description: 'Derived share of workers who work from home, useful for daytime at-home demand priors.',
  },
  [CENSUS_METRIC_KEYS.AGE_18_24_SHARE]: {
    metricKey: CENSUS_METRIC_KEYS.AGE_18_24_SHARE,
    metricLabel: 'Age 18 to 24 Share',
    metricCategory: 'demographic_profile',
    metricFamily: 'age',
    valueType: 'ratio',
    units: 'share',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: true,
    isActive: false,
    sourcePriority: 30,
    description: 'Optional derived share for identifying student-heavy and late-night-prone areas.',
  },
  [CENSUS_METRIC_KEYS.AGE_25_44_SHARE]: {
    metricKey: CENSUS_METRIC_KEYS.AGE_25_44_SHARE,
    metricLabel: 'Age 25 to 44 Share',
    metricCategory: 'demographic_profile',
    metricFamily: 'age',
    valueType: 'ratio',
    units: 'share',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: true,
    isActive: false,
    sourcePriority: 30,
    description: 'Optional derived share for identifying core working-age adult concentration.',
  },
  [CENSUS_METRIC_KEYS.AGE_65_PLUS_SHARE]: {
    metricKey: CENSUS_METRIC_KEYS.AGE_65_PLUS_SHARE,
    metricLabel: 'Age 65 Plus Share',
    metricCategory: 'demographic_profile',
    metricFamily: 'age',
    valueType: 'ratio',
    units: 'share',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: true,
    isActive: false,
    sourcePriority: 30,
    description: 'Optional derived share for identifying older population concentration.',
  },
  [CENSUS_METRIC_KEYS.STUDENT_SHARE]: {
    metricKey: CENSUS_METRIC_KEYS.STUDENT_SHARE,
    metricLabel: 'Student Share',
    metricCategory: 'demographic_profile',
    metricFamily: 'education',
    valueType: 'ratio',
    units: 'share',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'tract',
    isDerived: true,
    isActive: false,
    sourcePriority: 30,
    description: 'Optional derived share used to identify student-driven demand and college housing friction.',
  },
  [CENSUS_METRIC_KEYS.ZERO_VEHICLE_HOUSEHOLD_SHARE]: {
    metricKey: CENSUS_METRIC_KEYS.ZERO_VEHICLE_HOUSEHOLD_SHARE,
    metricLabel: 'Zero Vehicle Household Share',
    metricCategory: 'demand',
    metricFamily: 'vehicle_availability',
    valueType: 'ratio',
    units: 'share',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'block_group',
    isDerived: true,
    isActive: false,
    sourcePriority: 30,
    description: 'Optional derived share of households with no vehicle available, useful as a delivery-dependence proxy.',
  },
  [CENSUS_METRIC_KEYS.BROADBAND_ACCESS_SHARE]: {
    metricKey: CENSUS_METRIC_KEYS.BROADBAND_ACCESS_SHARE,
    metricLabel: 'Broadband Access Share',
    metricCategory: 'confidence',
    metricFamily: 'digital_access',
    valueType: 'ratio',
    units: 'share',
    sourceScope: 'derived',
    defaultH3Resolution: 7,
    preferredBoundaryType: 'tract',
    isDerived: true,
    isActive: false,
    sourcePriority: 40,
    description: 'Optional confidence modifier for sparse or rural markets based on broadband access.',
  },

  [REFERENCE_METRIC_KEYS.BOUNDARY]: {
    metricKey: REFERENCE_METRIC_KEYS.BOUNDARY,
    metricLabel: 'Administrative Boundary',
    metricCategory: 'reference',
    metricFamily: 'boundary',
    valueType: 'text',
    units: null,
    sourceScope: 'geojson_file',
    defaultH3Resolution: null,
    preferredBoundaryType: null,
    isDerived: false,
    isActive: true,
    sourcePriority: 10,
    description: 'Canonical reference boundary marker used for TIGER and other administrative geometry overlays.',
  },
  [REFERENCE_METRIC_KEYS.FLOOD_ZONE]: {
    metricKey: REFERENCE_METRIC_KEYS.FLOOD_ZONE,
    metricLabel: 'Flood Zone',
    metricCategory: 'risk',
    metricFamily: 'hazard',
    valueType: 'text',
    units: 'zone_code',
    sourceScope: 'geojson_file',
    defaultH3Resolution: 9,
    preferredBoundaryType: null,
    isDerived: false,
    isActive: true,
    sourcePriority: 15,
    description: 'FEMA flood hazard zone classification used for weather and routing risk overlays.',
  },
  [REFERENCE_METRIC_KEYS.CRASH_COUNT]: {
    metricKey: REFERENCE_METRIC_KEYS.CRASH_COUNT,
    metricLabel: 'Crash Count',
    metricCategory: 'risk',
    metricFamily: 'safety',
    valueType: 'count',
    units: 'fatalities',
    sourceScope: 'datagov_api',
    defaultH3Resolution: 9,
    preferredBoundaryType: null,
    isDerived: false,
    isActive: true,
    sourcePriority: 15,
    description: 'Aggregated crash/fatality count proxy used for roadway safety scoring overlays.',
  },
  [REFERENCE_METRIC_KEYS.TRAVEL_TIME_INDEX]: {
    metricKey: REFERENCE_METRIC_KEYS.TRAVEL_TIME_INDEX,
    metricLabel: 'Travel Time Index',
    metricCategory: 'transport',
    metricFamily: 'network',
    valueType: 'index',
    units: 'index',
    sourceScope: 'datagov_api',
    defaultH3Resolution: 9,
    preferredBoundaryType: null,
    isDerived: false,
    isActive: true,
    sourcePriority: 15,
    description: 'FHWA travel-time reliability index used for traffic congestion and route-friction overlays.',
  },
};

export function isKnownZoneMetricKey(value: string): value is ZoneMetricKey {
  return value in ZONE_METRIC_REGISTRY;
}

export function assertKnownZoneMetricKey(value: string): asserts value is ZoneMetricKey {
  if (!isKnownZoneMetricKey(value)) {
    throw new Error(`Unknown zone metric key: ${value}`);
  }
}

export function getZoneMetricDefinition(metricKey: string): ZoneMetricDefinition {
  const definition = ZONE_METRIC_REGISTRY[metricKey as ZoneMetricKey];
  if (!definition) {
    throw new Error(`Missing zone metric definition for key: ${metricKey}`);
  }
  return definition;
}
